#!/usr/bin/env python3

from scooter import *
from scooter.gcc import build_gcc
import argparse

here = dirof(__file__)

parser = argparse.ArgumentParser()
parser.add_argument('file', metavar='FILE', type=str)
args = parser.parse_args()

b = BuildHere(here)

sources = (
    here/'my-keyboard-layout.cpp',
    here/'my-physical-keyboard.cpp',
    p(args.file)
)

include = (
)

opts = (
    '-O3',
    '-g',
    '-std=c++17',
    '-Wall',
    '-Wno-unused-variable',
    '-Wno-unused-result',
    '-Werror',
)

libs = (
)

cpp = 'g++'

bin = b.mkobj(sources, '')

build_gcc(b, sources, bin, opts + include, gcc=cpp, libs=libs)

easyruntty(bin)

